# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: google/cloud-sdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2c:9f:ce:34:dd:df:74:fc:ec:24:c1:09:41:f7:db:0a"
      - run:
          name: Deploy Bot to GCE
          command: |
            ssh -o "StrictHostKeyChecking no" -t ubuntu@ec2-35-180-135-164.eu-west-3.compute.amazonaws.com "sudo rm -rf KyriosZolo && git clone https://github.com/apogiatzis/KyriosZolo && cd KyriosZolo && echo 'DISCORD_BOT_TOKEN='$DISCORD_BOT_TOKEN >> .env && echo 'WOLFRAM_ALPHA_APP_ID='$WOLFRAM_ALPHA_APP_ID >> .env && echo 'HTB_CREDS_EMAIL='$HTB_CREDS_EMAIL >> .env && echo 'HTB_CREDS_PASS='$HTB_CREDS_PASS >> .env && docker-compose up --build -d"
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master